// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jypvmulryqxtrbxdrlqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5cHZtdWxyeXF4dHJieGRybHFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk0Njk0ODgsImV4cCI6MjA5NTA0NTQ4OH0.miBuFxDY9FckOtXmD0MBcJchHv5HERpBfzzWng7su1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});